/*******************************************************************************
 *                                                                             *
 * Práctica 5 - Login                                                          *
 * Autor: Valle Guerra, Victor Leonardo                                        *
 * Proyecto: CARS(Car Automated Repair System)                                 *
 * [Major].[Minor].[Revision].[Build]                                          *
 * Versión : 1.0.0.0 (dev_release20210313_build_0)                             *
 * Nombre de Archivo: Menu.java                                                *
 * Fecha: 13/Abr/2021                                                          *
 * Materia: Seminario de solución de Problemas de Estructura de Datos II       *
 * NRC: 138619                                                                 *      
 * CVE: I5889                                                                  *
 * Sección: D21                                                                *
 * Profesor: Lupercio Coronel, Ramiro                                          *
 * Centro Universitario de Ciencias Exactas e Ingenierías                      *
 *                                                                             *
 ******************************************************************************/

// Paquete donde se incluye dicho archivo
package views;

// Parámetros que indican autor(es) de programa

import javax.swing.ImageIcon;
import models.Registro;
import models.Ventana;
import models.Usuario;

/**
 * @author Valle Guerra, Victor Leonardo 
 */

// Clase pública login que se extiende desde javax.swing.JFrame
public class Menu extends javax.swing.JFrame {

    /**
     * Parámetros a usar en clase
     * @param TamanoVentanaAAsignar
     * @param Registros
     */
    // |------------------------Atributos privados-----------------------------|
    private Ventana TamanoVentana;
    private Registro RegistrosVentana;
    private String ContrasenaTemp;
    private Boolean MostrandoContrasena;
    private Usuario SesionActiva;
    
    // |------------------------Métodos privados-------------------------------|
    
    // |------------------------Atributos públicos-----------------------------|
    
    // |------------------------Métodos públicos-------------------------------|
    
    /**
     * Constructor de clase que inicia ventana
     */

    public Menu(Ventana TamanoVentanaAAsignar, Registro Registros, Usuario Sesion) 
    {
        initComponents();
        // Pasar argumentos de constructor a atributos
        TamanoVentana = TamanoVentanaAAsignar;
        RegistrosVentana = Registros;
        MostrandoContrasena = false;
        SesionActiva = Sesion;
        this.ImagenUsuario.setText(SesionActiva.getNombreCompleto());
        // Colar imagen de icono de programa
        ImageIcon Icono = new ImageIcon(getClass().getResource(
            "/content/images/logo/CARS-Logo-IcosahedronTransparenteSinTexto.png"));
        setIconImage(Icono.getImage());
        // Pasa tamaño de ventana
        setSize((int) TamanoVentana.getAncho(), (int) TamanoVentana.getAltura());
        // Coloca al centro de la pantalla la ventana
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSuperiorIzquierdo = new javax.swing.JPanel();
        ImagenUsuario = new javax.swing.JLabel();
        ImagenLogo = new javax.swing.JLabel();
        PanelSuperior = new javax.swing.JPanel();
        PanelRuta = new javax.swing.JPanel();
        PanelRutaContenido = new javax.swing.JPanel();
        PanelSuperiorDerecho = new javax.swing.JPanel();
        PanelFechaHora = new javax.swing.JPanel();
        PanelFechaHoraContenido = new javax.swing.JPanel();
        Panelzquierdo = new javax.swing.JPanel();
        PanelUsuarios = new javax.swing.JPanel();
        BotonUsuarios = new javax.swing.JButton();
        PanelClientes = new javax.swing.JPanel();
        BotonClientes = new javax.swing.JButton();
        PanelVehiculos = new javax.swing.JPanel();
        BotonVehiculos = new javax.swing.JButton();
        PanelReparaciones = new javax.swing.JPanel();
        BotonReparaciones = new javax.swing.JButton();
        PanelPiezas = new javax.swing.JPanel();
        BotonPiezas = new javax.swing.JButton();
        PanelCerrarSesión = new javax.swing.JPanel();
        BotonCerrarSesion = new javax.swing.JButton();
        PanelCentral = new javax.swing.JPanel();
        PanelDerecho = new javax.swing.JPanel();
        PanelnferiorIzquierdo = new javax.swing.JPanel();
        PanelInferior = new javax.swing.JPanel();
        PanelInferiorDerecho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal | CARS");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));

        PanelSuperiorIzquierdo.setBackground(new java.awt.Color(17, 84, 128));
        PanelSuperiorIzquierdo.setMaximumSize(new java.awt.Dimension(384, 216));

        ImagenUsuario.setForeground(new java.awt.Color(238, 238, 238));
        ImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/menu/ImagenUsuario-EEEEEE-100x100.png"))); // NOI18N
        ImagenUsuario.setText("Usuario");
        ImagenUsuario.setToolTipText("<html><p><strong>Iniciar sesión</p></strong></html>");

        ImagenLogo.setBackground(new java.awt.Color(255, 255, 255));
        ImagenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/logo/CARS-Logo2.png"))); // NOI18N
        ImagenLogo.setToolTipText("<html><p><strong>Car Automated Repair System</strong></p></html>");

        javax.swing.GroupLayout PanelSuperiorIzquierdoLayout = new javax.swing.GroupLayout(PanelSuperiorIzquierdo);
        PanelSuperiorIzquierdo.setLayout(PanelSuperiorIzquierdoLayout);
        PanelSuperiorIzquierdoLayout.setHorizontalGroup(
            PanelSuperiorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 384, Short.MAX_VALUE)
            .addComponent(ImagenUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelSuperiorIzquierdoLayout.setVerticalGroup(
            PanelSuperiorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorIzquierdoLayout.createSequentialGroup()
                .addComponent(ImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImagenUsuario)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        getContentPane().add(PanelSuperiorIzquierdo);

        PanelSuperior.setLayout(new java.awt.GridLayout(2, 1));

        PanelRuta.setBackground(new java.awt.Color(41, 128, 185));

        javax.swing.GroupLayout PanelRutaLayout = new javax.swing.GroupLayout(PanelRuta);
        PanelRuta.setLayout(PanelRutaLayout);
        PanelRutaLayout.setHorizontalGroup(
            PanelRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        PanelRutaLayout.setVerticalGroup(
            PanelRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        PanelSuperior.add(PanelRuta);

        PanelRutaContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelRutaContenidoLayout = new javax.swing.GroupLayout(PanelRutaContenido);
        PanelRutaContenido.setLayout(PanelRutaContenidoLayout);
        PanelRutaContenidoLayout.setHorizontalGroup(
            PanelRutaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        PanelRutaContenidoLayout.setVerticalGroup(
            PanelRutaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        PanelSuperior.add(PanelRutaContenido);

        getContentPane().add(PanelSuperior);

        PanelSuperiorDerecho.setLayout(new java.awt.GridLayout(2, 1));

        PanelFechaHora.setBackground(new java.awt.Color(41, 128, 185));

        javax.swing.GroupLayout PanelFechaHoraLayout = new javax.swing.GroupLayout(PanelFechaHora);
        PanelFechaHora.setLayout(PanelFechaHoraLayout);
        PanelFechaHoraLayout.setHorizontalGroup(
            PanelFechaHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        PanelFechaHoraLayout.setVerticalGroup(
            PanelFechaHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        PanelSuperiorDerecho.add(PanelFechaHora);

        PanelFechaHoraContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelFechaHoraContenidoLayout = new javax.swing.GroupLayout(PanelFechaHoraContenido);
        PanelFechaHoraContenido.setLayout(PanelFechaHoraContenidoLayout);
        PanelFechaHoraContenidoLayout.setHorizontalGroup(
            PanelFechaHoraContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        PanelFechaHoraContenidoLayout.setVerticalGroup(
            PanelFechaHoraContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        PanelSuperiorDerecho.add(PanelFechaHoraContenido);

        getContentPane().add(PanelSuperiorDerecho);

        Panelzquierdo.setMaximumSize(new java.awt.Dimension(384, 432));
        Panelzquierdo.setLayout(new java.awt.GridLayout(3, 2));

        PanelUsuarios.setBackground(new java.awt.Color(59, 143, 255));
        PanelUsuarios.setMaximumSize(new java.awt.Dimension(192, 128));
        PanelUsuarios.setPreferredSize(new java.awt.Dimension(192, 128));

        BotonUsuarios.setBackground(new java.awt.Color(19, 140, 220));
        BotonUsuarios.setForeground(new java.awt.Color(238, 238, 238));
        BotonUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/menu/Usuarios-EEEEEE-24x24.png"))); // NOI18N
        BotonUsuarios.setText("Usuarios");
        BotonUsuarios.setToolTipText("<html><p><strong>Usuarios</strong></p></html>");
        BotonUsuarios.setBorder(null);
        BotonUsuarios.setBorderPainted(false);
        BotonUsuarios.setContentAreaFilled(false);
        BotonUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonUsuarios.setFocusPainted(false);

        javax.swing.GroupLayout PanelUsuariosLayout = new javax.swing.GroupLayout(PanelUsuarios);
        PanelUsuarios.setLayout(PanelUsuariosLayout);
        PanelUsuariosLayout.setHorizontalGroup(
            PanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuariosLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(BotonUsuarios)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        PanelUsuariosLayout.setVerticalGroup(
            PanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonUsuarios)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        Panelzquierdo.add(PanelUsuarios);

        PanelClientes.setBackground(new java.awt.Color(19, 140, 220));
        PanelClientes.setMaximumSize(new java.awt.Dimension(192, 128));
        PanelClientes.setPreferredSize(new java.awt.Dimension(192, 128));

        BotonClientes.setBackground(new java.awt.Color(19, 140, 220));
        BotonClientes.setForeground(new java.awt.Color(238, 238, 238));
        BotonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/menu/Clientes-EEEEEE-24x24.png"))); // NOI18N
        BotonClientes.setText("Clientes");
        BotonClientes.setToolTipText("<html><p><strong>Clientes</strong></p></html>");
        BotonClientes.setBorder(null);
        BotonClientes.setBorderPainted(false);
        BotonClientes.setContentAreaFilled(false);
        BotonClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonClientes.setFocusPainted(false);
        BotonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelClientesLayout = new javax.swing.GroupLayout(PanelClientes);
        PanelClientes.setLayout(PanelClientesLayout);
        PanelClientesLayout.setHorizontalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(BotonClientes)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        PanelClientesLayout.setVerticalGroup(
            PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonClientes)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        Panelzquierdo.add(PanelClientes);

        PanelVehiculos.setBackground(new java.awt.Color(19, 140, 220));
        PanelVehiculos.setMaximumSize(new java.awt.Dimension(192, 128));
        PanelVehiculos.setPreferredSize(new java.awt.Dimension(192, 128));

        BotonVehiculos.setBackground(new java.awt.Color(19, 140, 220));
        BotonVehiculos.setForeground(new java.awt.Color(238, 238, 238));
        BotonVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/menu/Vehiculos-EEEEEE-24x24.png"))); // NOI18N
        BotonVehiculos.setText("Vehículos");
        BotonVehiculos.setToolTipText("<html><p><strong>Vehículos</strong></p></html>");
        BotonVehiculos.setBorder(null);
        BotonVehiculos.setBorderPainted(false);
        BotonVehiculos.setContentAreaFilled(false);
        BotonVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVehiculos.setFocusPainted(false);
        BotonVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVehiculosLayout = new javax.swing.GroupLayout(PanelVehiculos);
        PanelVehiculos.setLayout(PanelVehiculosLayout);
        PanelVehiculosLayout.setHorizontalGroup(
            PanelVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVehiculosLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(BotonVehiculos)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        PanelVehiculosLayout.setVerticalGroup(
            PanelVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVehiculosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonVehiculos)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        Panelzquierdo.add(PanelVehiculos);

        PanelReparaciones.setBackground(new java.awt.Color(19, 140, 220));
        PanelReparaciones.setMaximumSize(new java.awt.Dimension(192, 128));
        PanelReparaciones.setPreferredSize(new java.awt.Dimension(192, 128));

        BotonReparaciones.setBackground(new java.awt.Color(19, 140, 220));
        BotonReparaciones.setForeground(new java.awt.Color(238, 238, 238));
        BotonReparaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/menu/Reparaciones-EEEEEE-24x24.png"))); // NOI18N
        BotonReparaciones.setText("Reparaciones");
        BotonReparaciones.setToolTipText("<html><p><strong>Reparaciones</strong></p></html>");
        BotonReparaciones.setBorder(null);
        BotonReparaciones.setBorderPainted(false);
        BotonReparaciones.setContentAreaFilled(false);
        BotonReparaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonReparaciones.setFocusPainted(false);
        BotonReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReparacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelReparacionesLayout = new javax.swing.GroupLayout(PanelReparaciones);
        PanelReparaciones.setLayout(PanelReparacionesLayout);
        PanelReparacionesLayout.setHorizontalGroup(
            PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReparacionesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BotonReparaciones)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        PanelReparacionesLayout.setVerticalGroup(
            PanelReparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelReparacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonReparaciones)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        Panelzquierdo.add(PanelReparaciones);

        PanelPiezas.setBackground(new java.awt.Color(19, 140, 220));
        PanelPiezas.setMaximumSize(new java.awt.Dimension(192, 128));
        PanelPiezas.setPreferredSize(new java.awt.Dimension(192, 128));

        BotonPiezas.setBackground(new java.awt.Color(19, 140, 220));
        BotonPiezas.setForeground(new java.awt.Color(238, 238, 238));
        BotonPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/menu/Piezas-EEEEEE-24x24.png"))); // NOI18N
        BotonPiezas.setText("Piezas");
        BotonPiezas.setToolTipText("<html><p><strong>Piezas</strong></p></html>");
        BotonPiezas.setBorder(null);
        BotonPiezas.setBorderPainted(false);
        BotonPiezas.setContentAreaFilled(false);
        BotonPiezas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPiezas.setFocusPainted(false);
        BotonPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPiezasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPiezasLayout = new javax.swing.GroupLayout(PanelPiezas);
        PanelPiezas.setLayout(PanelPiezasLayout);
        PanelPiezasLayout.setHorizontalGroup(
            PanelPiezasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
            .addGroup(PanelPiezasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelPiezasLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(BotonPiezas)
                    .addContainerGap(74, Short.MAX_VALUE)))
        );
        PanelPiezasLayout.setVerticalGroup(
            PanelPiezasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
            .addGroup(PanelPiezasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelPiezasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BotonPiezas)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        Panelzquierdo.add(PanelPiezas);

        PanelCerrarSesión.setBackground(new java.awt.Color(19, 140, 220));
        PanelCerrarSesión.setMaximumSize(new java.awt.Dimension(192, 128));
        PanelCerrarSesión.setPreferredSize(new java.awt.Dimension(192, 128));

        BotonCerrarSesion.setBackground(new java.awt.Color(19, 140, 220));
        BotonCerrarSesion.setForeground(new java.awt.Color(238, 238, 238));
        BotonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/content/images/menu/CerrarSesion-EEEEEE-24x24.png"))); // NOI18N
        BotonCerrarSesion.setText("Cerrar Sesión");
        BotonCerrarSesion.setToolTipText("<html><p><strong>Cerrar sesión</strong></p></html>");
        BotonCerrarSesion.setBorder(null);
        BotonCerrarSesion.setBorderPainted(false);
        BotonCerrarSesion.setContentAreaFilled(false);
        BotonCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCerrarSesion.setFocusPainted(false);
        BotonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCerrarSesiónLayout = new javax.swing.GroupLayout(PanelCerrarSesión);
        PanelCerrarSesión.setLayout(PanelCerrarSesiónLayout);
        PanelCerrarSesiónLayout.setHorizontalGroup(
            PanelCerrarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
            .addGroup(PanelCerrarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCerrarSesiónLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(BotonCerrarSesion)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );
        PanelCerrarSesiónLayout.setVerticalGroup(
            PanelCerrarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
            .addGroup(PanelCerrarSesiónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCerrarSesiónLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BotonCerrarSesion)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        Panelzquierdo.add(PanelCerrarSesión);

        getContentPane().add(Panelzquierdo);

        PanelCentral.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelCentralLayout = new javax.swing.GroupLayout(PanelCentral);
        PanelCentral.setLayout(PanelCentralLayout);
        PanelCentralLayout.setHorizontalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        PanelCentralLayout.setVerticalGroup(
            PanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(PanelCentral);

        PanelDerecho.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelDerechoLayout = new javax.swing.GroupLayout(PanelDerecho);
        PanelDerecho.setLayout(PanelDerechoLayout);
        PanelDerechoLayout.setHorizontalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        PanelDerechoLayout.setVerticalGroup(
            PanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(PanelDerecho);

        PanelnferiorIzquierdo.setBackground(new java.awt.Color(17, 84, 128));
        PanelnferiorIzquierdo.setMaximumSize(new java.awt.Dimension(384, 432));

        javax.swing.GroupLayout PanelnferiorIzquierdoLayout = new javax.swing.GroupLayout(PanelnferiorIzquierdo);
        PanelnferiorIzquierdo.setLayout(PanelnferiorIzquierdoLayout);
        PanelnferiorIzquierdoLayout.setHorizontalGroup(
            PanelnferiorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        PanelnferiorIzquierdoLayout.setVerticalGroup(
            PanelnferiorIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(PanelnferiorIzquierdo);

        PanelInferior.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelInferiorLayout = new javax.swing.GroupLayout(PanelInferior);
        PanelInferior.setLayout(PanelInferiorLayout);
        PanelInferiorLayout.setHorizontalGroup(
            PanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        PanelInferiorLayout.setVerticalGroup(
            PanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(PanelInferior);

        PanelInferiorDerecho.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelInferiorDerechoLayout = new javax.swing.GroupLayout(PanelInferiorDerecho);
        PanelInferiorDerecho.setLayout(PanelInferiorDerechoLayout);
        PanelInferiorDerechoLayout.setHorizontalGroup(
            PanelInferiorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        PanelInferiorDerechoLayout.setVerticalGroup(
            PanelInferiorDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(PanelInferiorDerecho);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReparacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonReparacionesActionPerformed

    private void BotonVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonVehiculosActionPerformed

    private void BotonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonClientesActionPerformed

    private void BotonPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPiezasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPiezasActionPerformed

    // Método para cuando se hace click en BotonCerrarSesion
    private void BotonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarSesionActionPerformed
        System.out.println("Cerrando Sesión " + SesionActiva.getUsername());
        Login LoginVentana = new Login(TamanoVentana, RegistrosVentana);
        LoginVentana.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana TamanoVentana;
                Registro Registros;
                Registros = new Registro();
                TamanoVentana = new Ventana();
                Usuario UsuarioTemp = new Usuario();
                new Menu(TamanoVentana, Registros , UsuarioTemp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrarSesion;
    private javax.swing.JButton BotonClientes;
    private javax.swing.JButton BotonPiezas;
    private javax.swing.JButton BotonReparaciones;
    private javax.swing.JButton BotonUsuarios;
    private javax.swing.JButton BotonVehiculos;
    private javax.swing.JLabel ImagenLogo;
    private javax.swing.JLabel ImagenUsuario;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelCerrarSesión;
    private javax.swing.JPanel PanelClientes;
    private javax.swing.JPanel PanelDerecho;
    private javax.swing.JPanel PanelFechaHora;
    private javax.swing.JPanel PanelFechaHoraContenido;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel PanelInferiorDerecho;
    private javax.swing.JPanel PanelPiezas;
    private javax.swing.JPanel PanelReparaciones;
    private javax.swing.JPanel PanelRuta;
    private javax.swing.JPanel PanelRutaContenido;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JPanel PanelSuperiorDerecho;
    private javax.swing.JPanel PanelSuperiorIzquierdo;
    private javax.swing.JPanel PanelUsuarios;
    private javax.swing.JPanel PanelVehiculos;
    private javax.swing.JPanel PanelnferiorIzquierdo;
    private javax.swing.JPanel Panelzquierdo;
    // End of variables declaration//GEN-END:variables
}
